title: Kelompok 2
logo: /assets/img/scope.png
description: Kami kelompok 2 Link and Match STT Terpadu Nurul Fikri
Dengan Anggota :
        Herlina
        Rafi
        Hauzani
        Yazid
        Shidqi
        Raihan


show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# title: Minimal theme
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal
