title: Kelompok 2
logo: /assets/img/logo.png
description: Dari Link and Match STT Terpadu Nurul Fikri
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# title: Minimal theme
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal
